name: siemens_ix_flutter
description: "Siemens iX Design System."
version: 0.0.1
homepage: empty

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.6.0
  yaml: ^3.1.3
  path: ^1.9.1
  args: ^2.7.0
  recase: ^4.1.0
  meta: ^1.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  fonts:
    - family: Siemens Sans
      fonts:
        - asset: assets/fonts/siemens/sisan03.ttf
          weight: 400
        - asset: assets/fonts/siemens/sisan06.ttf
          weight: 700
        - asset: assets/fonts/siemens/sisan33.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/siemens/sisan36.ttf
          weight: 700
          style: italic
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
