name: ix_flutter
description: "Flutter UI library implementing Siemens iX Design System with 1400+ icons, themes, and widgets for all platforms."
version: 1.0.3
homepage: https://github.com/SobSoft-s-r-o/ix_flutter
repository: https://github.com/SobSoft-s-r-o/ix_flutter
issue_tracker: https://github.com/SobSoft-s-r-o/ix_flutter/issues
documentation: https://github.com/SobSoft-s-r-o/ix_flutter/wiki

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.6.0
  yaml: ^3.1.3
  path: ^1.9.1
  args: ^2.7.0
  recase: ^4.1.0
  meta: ^1.17.0
  archive: ^4.0.7

topics:
  - flutter
  - ui-kit
  - widgets
  - design-system
  - icons

executables:
  generate_icons: generate_icons

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JetBrains_Mono/static/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
