name: siemens_ix_icons_generator
description: Icon generator tool for Siemens iX Design System Flutter package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  http: ^1.6.0
  path: ^1.9.1
  recase: ^4.1.0
  archive: ^4.0.7
  args: ^2.7.0

executables:
  generate_ix_icons: generate_icons
